// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wC_GCVYvhqmRE6v3zjgwKfg6Q5ejdAk',
    appId: '1:23297746199:web:2f1d7b2fc83d5498010352',
    messagingSenderId: '23297746199',
    projectId: 'ease-58369',
    authDomain: 'ease-58369.firebaseapp.com',
    storageBucket: 'ease-58369.firebasestorage.app',
    measurementId: 'G-L0MCMPRYH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9py2HHCy6VuNpuKVkadx_wJmuPNHjL_s',
    appId: '1:23297746199:android:036498ce334226d0010352',
    messagingSenderId: '23297746199',
    projectId: 'ease-58369',
    storageBucket: 'ease-58369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhgEbHOW4U_4Nl69eSKQrNZGC1NqzKw0',
    appId: '1:23297746199:ios:6047baa1f3ac825b010352',
    messagingSenderId: '23297746199',
    projectId: 'ease-58369',
    storageBucket: 'ease-58369.firebasestorage.app',
    androidClientId: '23297746199-lnkktjrq1dbqgamsmqre1pf4ct73d5r9.apps.googleusercontent.com',
    iosClientId: '23297746199-cearpt2md0i9rsq2iaquagmtbqoc2km0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoadmins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhgEbHOW4U_4Nl69eSKQrNZGC1NqzKw0',
    appId: '1:23297746199:ios:6047baa1f3ac825b010352',
    messagingSenderId: '23297746199',
    projectId: 'ease-58369',
    storageBucket: 'ease-58369.firebasestorage.app',
    androidClientId: '23297746199-lnkktjrq1dbqgamsmqre1pf4ct73d5r9.apps.googleusercontent.com',
    iosClientId: '23297746199-cearpt2md0i9rsq2iaquagmtbqoc2km0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoadmins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-wC_GCVYvhqmRE6v3zjgwKfg6Q5ejdAk',
    appId: '1:23297746199:web:aafac8d77cdac6c7010352',
    messagingSenderId: '23297746199',
    projectId: 'ease-58369',
    authDomain: 'ease-58369.firebaseapp.com',
    storageBucket: 'ease-58369.firebasestorage.app',
    measurementId: 'G-8QCLFT75VZ',
  );
}
